### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by Keith94** [ThirteenAG/thirteenag.github.io#1]
Possible to add search bar to quickly find a particular plugin?

**Comment by ThirteenAG** [comment]
I thought about it, not sure how to do search on a single page application, but maybe at some point I'll look into it.

**Comment by ThirteenAG** [comment]
Added a small search field with generated list of fixes, can search by partial match of a name or a tag.

**Comment by Keith94** [comment]
Perfect! Should be very useful for navigating the site.
